### ISSUE TITLE
Error upon example package import

### ISSUE THREAD

**Issue by brookinsconsulting** [mugoweb/mugo_calendar#1]
Error:
Call to a member function unserializeContentClassAttribute() on null in /home/se7enx/web/doc/vh/rar/rar/ezpublish_legacy/kernel/classes/packagehandlers/ezcontentclass/ezcontentclasspackagehandler.php on line 383

**Comment by pkamps** [comment]
The package was outdated. We decided to remove the package from the code base. It's easy enough to just add the new datatype to an existing content class. Documentation was updated in 235f53aeb4d7abf22b0ac40dd5bac951ce94a101
