### ISSUE TITLE
Missing Extension Dependencies

### ISSUE THREAD

**Issue by brookinsconsulting** [mugoweb/mugo_calendar#2]
Hello,

This repository depends upon but does not provide the datatype, Mugo Calendar Event as referenced in the README instructions and package contents.

Could you please provide the extension which provides the Mugo Calendar Event?

Respectfully,
Brookins Consulting

**Comment by peterkeung** [comment]
That datatype has been merged into the mugorecurringevent datatype.

@pkamps should we just remove the package and the reference to it? It should be straightforward to just add the new field to a content class.

**Comment by pkamps** [comment]
OK, I'll do the updates in the next days. Thanks for the feedback @brookinsconsulting

**Comment by brookinsconsulting** [comment]
@peterkeung the templates must surely depend upon a specific class attribute identifier being used to see the calendar, which I've yet to see. how about a screenshot and show longer template installation and usage instructions.

**Comment by brookinsconsulting** [comment]
![Screenshot 2023-01-30 at 13-11-17 Events _ About - ikorcafe com](https://user-images.githubusercontent.com/617031/215596229-8bfc41f7-b424-4a4f-9440-4930e8136989.png)

Hello again, I am getting some errors when trying to use the agenda include template and I'm really not sure how to fix these errors in debug mode.

**Comment by pkamps** [comment]
The agenda issue should probably be a separate one.

**Comment by brookinsconsulting** [comment]
Agreed

**Comment by brookinsconsulting** [comment]
I wrote a new separate issue #3 this issue can be closed as completed
