### ISSUE TITLE
Capitalize first word

### ISSUE THREAD

**Issue by brookinsconsulting** [mugoweb/mugo_calendar#4]
Hello @pkamps I found that the lower case was undesirable since this is used by itself usually as an identifier of sorts to the end user.

Here is a quick patch of the change we made for the shop using this solution.

`diff --git a/classes/MugoRecurrence.php b/classes/MugoRecurrence.php
index 3d01b3a..8575252 100644
--- a/classes/MugoRecurrence.php
+++ b/classes/MugoRecurrence.php
@@ -299,7 +299,7 @@ class MugoRecurrence
      */
     public function describe( $dateFormat = '%Y-%m-%d' )
     {
-        $return = ezpI18n::tr( 'mugo_calendar_date_description', 'every' ) . ' ';
+        $return = ezpI18n::tr( 'mugo_calendar_date_description', 'Every' ) . ' ';
 
         if( $this->type == 'Weekly' )
         {
`

Cheers,
Brookins Consulting

**Comment by pkamps** [comment]
Changed
